# SITE SETTINGS
title: Conference Notes             # Title in top navigation bar (navbar) and <head>
author: Damiano Oldoni              # Used for copyright statement in footer
baseurl: "/notes"                   # Only required if your site is in a directory e.g. https://username.github.io/sitename
                                    # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                    # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/markdown/#links


# SOCIAL PROFILES
social:
  email: damiano.oldoni@inbo.be
  github: damianooldoni               # Can also be a github_username/repository
  mastodon: https://fosstodon.org/@damianooldoni

# THEME SETTINGS (ALL OPTIONAL)

remote_theme: peterdesmet/petridish@3.0

# BUILD SETTINGS
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec