# SITE SETTINGS
title: Conference Notes             # Title in top navigation bar (navbar) and <head>
author: Damiano Oldoni              # Used for copyright statement in footer
baseurl: "/notes"                   # Only required if your site is in a directory e.g. https://username.github.io/sitename
                                    # which has url: "https://username.github.io" (no slash) and baseurl: "/sitename" (leading slash)
                                    # A baseurl affects internal links, see http://peterdesmet.github.io/petridish/markdown/#links


# SOCIAL PROFILES
social:
  email: damiano.oldoni@inbo.be
  github: damianooldoni               # Can also be a github_username/repository
  mastodon: https://fosstodon.org/@damianooldoni

# THEME SETTINGS (ALL OPTIONAL)

posts_on_home: 4                        # Show x number of latest posts on homepage, can be 0
archive_permalink: /blog/
remote_theme: peterdesmet/petridish@3.0
logo: /assets/themes/images/logo.png
github_edit: true

# BUILD SETTINGS
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - LICENSE
  - package-lock.json
  - package.json
  - petridish.gemspec

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default                   # Use default.html layout by default for all files